### ISSUE TITLE
Submodule URL is not listed

### ISSUE THREAD

**Issue by RichardMuri** [IntelLabs/PreSiFuzz#25]
For latest commit on main (3da13ce)
Error:
`fatal: No url found for submodule path 'libpresifuzz_riscv/src/riscv-opcodes' in .gitmodules`

Steps to reproduce:
```
    git clone  https://github.com/IntelLabs/PreSiFuzz  
    cd PreSiFuzz  
    git submodule update --init  
```

**Comment by Bounti** [comment]
Thanks for reporting.
I just fixed the issue with #29
